"""identity, meetings, work, games and the record

Revision ID: 143b9ac0f90f
Revises: 0001_initial
Create Date: 2026-09-30 10:58:04.230570
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '143b9ac0f90f'
down_revision: str | None = '0001_initial'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('emoji', sa.String(length=8), nullable=False),
    sa.Column('criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rarity', sa.String(length=16), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_achievements')),
    sa.UniqueConstraint('key', name=op.f('uq_achievements_key'))
    )
    op.create_table('game_definitions',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('family', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('config_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('min_players', sa.Integer(), nullable=False),
    sa.Column('max_players', sa.Integer(), nullable=True),
    sa.Column('typical_minutes', sa.Integer(), nullable=False),
    sa.Column('energy', sa.String(length=16), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('how_to_play', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("family IN ('prompt_deck', 'host_quiz', 'host_scored')", name=op.f('ck_game_definitions_family_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_game_definitions')),
    sa.UniqueConstraint('key', name=op.f('uq_game_definitions_key'))
    )
    op.create_table('organizations',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations')),
    sa.UniqueConstraint('slug', name=op.f('uq_organizations_slug'))
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('leaderboard_opt_out', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('xp_rules',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('max_per_session', sa.Integer(), nullable=True),
    sa.Column('max_per_day', sa.Integer(), nullable=True),
    sa.Column('max_per_week', sa.Integer(), nullable=True),
    sa.Column('diminishing_after', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_xp_rules')),
    sa.UniqueConstraint('key', name=op.f('uq_xp_rules_key'))
    )
    op.create_table('auth_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_auth_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_auth_sessions_token_hash'))
    )
    op.create_index(op.f('ix_auth_sessions_user_id'), 'auth_sessions', ['user_id'], unique=False)
    op.create_table('content_packs',
    sa.Column('game_definition_key', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('license', sa.String(length=120), nullable=False),
    sa.Column('attribution', sa.String(length=200), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('is_seed', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_content_packs_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['game_definition_key'], ['game_definitions.key'], name=op.f('fk_content_packs_game_definition_key_game_definitions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_packs')),
    sa.UniqueConstraint('key', name=op.f('uq_content_packs_key'))
    )
    op.create_index(op.f('ix_content_packs_game_definition_key'), 'content_packs', ['game_definition_key'], unique=False)
    op.create_table('teams',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_teams_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams')),
    sa.UniqueConstraint('slug', name=op.f('uq_teams_slug'))
    )
    op.create_table('comments',
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('target_type', sa.String(length=16), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('author_name', sa.String(length=120), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("target_type IN ('idea', 'decision', 'task', 'blocker', 'session')", name=op.f('ck_comments_comment_target_valid')),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_comments_author_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_comments_team_id_teams'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comments'))
    )
    op.create_index('ix_comments_target', 'comments', ['target_type', 'target_id', 'created_at'], unique=False)
    op.create_table('game_questions',
    sa.Column('content_pack_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('choices', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('media_url', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.Column('difficulty', sa.String(length=16), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['content_pack_id'], ['content_packs.id'], name=op.f('fk_game_questions_content_pack_id_content_packs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_game_questions')),
    sa.UniqueConstraint('content_pack_id', 'position', name='uq_question_position')
    )
    op.create_table('guests',
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('linked_user_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_guests_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['linked_user_id'], ['users.id'], name=op.f('fk_guests_linked_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_guests_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guests'))
    )
    op.create_index(op.f('ix_guests_team_id'), 'guests', ['team_id'], unique=False)
    op.create_table('invites',
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['accepted_by'], ['users.id'], name=op.f('fk_invites_accepted_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], name=op.f('fk_invites_invited_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_invites_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invites')),
    sa.UniqueConstraint('code', name=op.f('uq_invites_code'))
    )
    op.create_index(op.f('ix_invites_team_id'), 'invites', ['team_id'], unique=False)
    op.create_table('memberships',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_memberships_team_id_teams'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_memberships_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memberships')),
    sa.UniqueConstraint('user_id', 'team_id', name='uq_memberships_user_team')
    )
    op.create_index(op.f('ix_memberships_team_id'), 'memberships', ['team_id'], unique=False)
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_notifications_team_id_teams'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('projects',
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('active', 'paused', 'done')", name=op.f('ck_projects_status_valid')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_projects_owner_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_projects_team_id_teams'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_table('seasons',
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('upcoming', 'active', 'closed')", name=op.f('ck_seasons_status_valid')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_seasons_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seasons'))
    )
    op.create_index(op.f('ix_seasons_team_id'), 'seasons', ['team_id'], unique=False)
    op.create_table('sessions',
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('facilitator_id', sa.UUID(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('summary_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('summary_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('planned', 'active', 'paused', 'completed', 'cancelled')", name=op.f('ck_sessions_status_valid')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_sessions_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['facilitator_id'], ['users.id'], name=op.f('fk_sessions_facilitator_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_sessions_team_id_teams'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions')),
    sa.UniqueConstraint('team_id', 'sequence_no', name='uq_sessions_team_sequence')
    )
    op.create_index(op.f('ix_sessions_status'), 'sessions', ['status'], unique=False)
    op.create_index('uq_sessions_one_active_per_team', 'sessions', ['team_id'], unique=True, postgresql_where=sa.text("status = 'active' AND deleted_at IS NULL"))
    op.create_table('achievement_awards',
    sa.Column('achievement_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('guest_id', sa.UUID(), nullable=True),
    sa.Column('season_id', sa.UUID(), nullable=True),
    sa.Column('awarded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('awarded_by', sa.UUID(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoke_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], name=op.f('fk_achievement_awards_achievement_id_achievements'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['awarded_by'], ['users.id'], name=op.f('fk_achievement_awards_awarded_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], name=op.f('fk_achievement_awards_guest_id_guests'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], name=op.f('fk_achievement_awards_season_id_seasons'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_achievement_awards_team_id_teams'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_achievement_awards_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_achievement_awards'))
    )
    op.create_index('ix_achievement_awards_subject', 'achievement_awards', ['team_id', 'user_id'], unique=False)
    op.create_table('activity',
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_name', sa.String(length=120), nullable=False),
    sa.Column('verb', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('visibility', sa.String(length=16), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("actor_type IN ('user', 'guest', 'system')", name=op.f('ck_activity_actor_type_valid')),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_activity_session_id_sessions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_activity_team_id_teams'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity'))
    )
    op.create_index('ix_activity_session_occurred', 'activity', ['session_id', 'occurred_at'], unique=False)
    op.create_index('ix_activity_target', 'activity', ['target_type', 'target_id', 'occurred_at'], unique=False)
    op.create_index('ix_activity_team_occurred', 'activity', ['team_id', 'occurred_at'], unique=False)
    op.create_table('agenda_items',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('timebox_minutes', sa.Integer(), nullable=True),
    sa.Column('covered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_agenda_items_session_id_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agenda_items'))
    )
    op.create_index(op.f('ix_agenda_items_session_id'), 'agenda_items', ['session_id'], unique=False)
    op.create_table('game_plays',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('game_definition_key', sa.String(length=64), nullable=False),
    sa.Column('content_pack_id', sa.UUID(), nullable=True),
    sa.Column('host_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('question_order', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('current_index', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'running', 'finished', 'abandoned')", name=op.f('ck_game_plays_status_valid')),
    sa.ForeignKeyConstraint(['content_pack_id'], ['content_packs.id'], name=op.f('fk_game_plays_content_pack_id_content_packs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['game_definition_key'], ['game_definitions.key'], name=op.f('fk_game_plays_game_definition_key_game_definitions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], name=op.f('fk_game_plays_host_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_game_plays_session_id_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_game_plays'))
    )
    op.create_index('ix_game_plays_session', 'game_plays', ['session_id'], unique=False)
    op.create_table('ideas',
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('author_name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('converted_to_type', sa.String(length=16), nullable=True),
    sa.Column('converted_to_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('new', 'discussing', 'accepted', 'parked', 'rejected', 'converted')", name=op.f('ck_ideas_status_valid')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_ideas_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_ideas_session_id_sessions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_ideas_team_id_teams'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ideas'))
    )
    op.create_index('ix_ideas_session', 'ideas', ['session_id'], unique=False)
    op.create_index('ix_ideas_team_status', 'ideas', ['team_id', 'status'], unique=False)
    op.create_table('session_participants',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('guest_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('attended', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('user_id IS NOT NULL OR guest_id IS NOT NULL', name=op.f('ck_session_participants_session_participant_is_a_person')),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], name=op.f('fk_session_participants_guest_id_guests'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_session_participants_session_id_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_session_participants_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_participants')),
    sa.UniqueConstraint('session_id', 'user_id', name='uq_session_your_participant')
    )
    op.create_index(op.f('ix_session_participants_session_id'), 'session_participants', ['session_id'], unique=False)
    op.create_table('xp_events',
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('guest_id', sa.UUID(), nullable=True),
    sa.Column('subject_name', sa.String(length=120), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('reason_key', sa.String(length=64), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('awarded_by', sa.UUID(), nullable=True),
    sa.Column('season_id', sa.UUID(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('user_id IS NOT NULL OR guest_id IS NOT NULL', name=op.f('ck_xp_events_xp_has_a_subject')),
    sa.ForeignKeyConstraint(['awarded_by'], ['users.id'], name=op.f('fk_xp_events_awarded_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], name=op.f('fk_xp_events_guest_id_guests'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], name=op.f('fk_xp_events_season_id_seasons'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_xp_events_session_id_sessions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_xp_events_team_id_teams'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_xp_events_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_xp_events')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_xp_events_idempotency_key'))
    )
    op.create_index('ix_xp_events_leaderboard', 'xp_events', ['team_id', 'season_id', 'user_id'], unique=False)
    op.create_index('ix_xp_events_subject_time', 'xp_events', ['user_id', 'occurred_at'], unique=False)
    op.create_table('decisions',
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('idea_id', sa.UUID(), nullable=True),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('decided_by', sa.UUID(), nullable=True),
    sa.Column('decided_by_name', sa.String(length=120), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('supersedes_id', sa.UUID(), nullable=True),
    sa.Column('superseded_by_id', sa.UUID(), nullable=True),
    sa.Column('standalone_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('session_id IS NOT NULL OR standalone_reason IS NOT NULL', name=op.f('ck_decisions_decision_has_context')),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], name=op.f('fk_decisions_decided_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], name=op.f('fk_decisions_idea_id_ideas'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_decisions_session_id_sessions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['decisions.id'], name=op.f('fk_decisions_superseded_by_id_decisions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supersedes_id'], ['decisions.id'], name=op.f('fk_decisions_supersedes_id_decisions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_decisions_team_id_teams'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decisions'))
    )
    op.create_index('ix_decisions_team', 'decisions', ['team_id', 'decided_at'], unique=False)
    op.create_table('game_scores',
    sa.Column('game_play_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('guest_id', sa.UUID(), nullable=True),
    sa.Column('player_name', sa.String(length=120), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=8), nullable=False),
    sa.Column('adjusted_by', sa.UUID(), nullable=True),
    sa.Column('adjustment_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('auto', 'host')", name=op.f('ck_game_scores_source_valid')),
    sa.CheckConstraint('user_id IS NOT NULL OR guest_id IS NOT NULL', name=op.f('ck_game_scores_score_has_a_player')),
    sa.ForeignKeyConstraint(['adjusted_by'], ['users.id'], name=op.f('fk_game_scores_adjusted_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['game_play_id'], ['game_plays.id'], name=op.f('fk_game_scores_game_play_id_game_plays'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], name=op.f('fk_game_scores_guest_id_guests'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_game_scores_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_game_scores'))
    )
    op.create_index(op.f('ix_game_scores_game_play_id'), 'game_scores', ['game_play_id'], unique=False)
    op.create_table('idea_tags',
    sa.Column('idea_id', sa.UUID(), nullable=False),
    sa.Column('tag', sa.String(length=60), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], name=op.f('fk_idea_tags_idea_id_ideas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_idea_tags')),
    sa.UniqueConstraint('idea_id', 'tag', name='uq_idea_tags_idea_tag')
    )
    op.create_index(op.f('ix_idea_tags_idea_id'), 'idea_tags', ['idea_id'], unique=False)
    op.create_table('tasks',
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('idea_id', sa.UUID(), nullable=True),
    sa.Column('decision_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("owner_id IS NOT NULL OR status IN ('backlog', 'cancelled')", name=op.f('ck_tasks_owner_required_outside_backlog')),
    sa.CheckConstraint("priority IN ('low', 'normal', 'high', 'urgent')", name=op.f('ck_tasks_priority_valid')),
    sa.CheckConstraint("status IN ('backlog', 'in_progress', 'blocked', 'done', 'cancelled')", name=op.f('ck_tasks_status_valid')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_tasks_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], name=op.f('fk_tasks_decision_id_decisions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], name=op.f('fk_tasks_idea_id_ideas'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_tasks_owner_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_tasks_project_id_projects'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_tasks_session_id_sessions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_tasks_team_id_teams'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    op.create_index('ix_tasks_origin', 'tasks', ['idea_id', 'decision_id'], unique=False)
    op.create_index('ix_tasks_owner_status', 'tasks', ['owner_id', 'status'], unique=False)
    op.create_index('ix_tasks_project', 'tasks', ['project_id'], unique=False)
    op.create_index('ix_tasks_session', 'tasks', ['session_id'], unique=False)
    op.create_index('ix_tasks_team_status_due', 'tasks', ['team_id', 'status', 'due_date'], unique=False)
    op.create_table('blockers',
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('idea_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('raised_by', sa.UUID(), nullable=True),
    sa.Column('raised_by_name', sa.String(length=120), nullable=False),
    sa.Column('raised_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolved_by_name', sa.String(length=120), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('task_id IS NOT NULL OR idea_id IS NOT NULL', name=op.f('ck_blockers_blocker_has_a_target')),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], name=op.f('fk_blockers_idea_id_ideas'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raised_by'], ['users.id'], name=op.f('fk_blockers_raised_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], name=op.f('fk_blockers_resolved_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_blockers_task_id_tasks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_blockers_team_id_teams'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blockers'))
    )
    op.create_index('ix_blockers_open', 'blockers', ['team_id', 'resolved_at'], unique=False)
    op.create_table('task_collaborators',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_task_collaborators_task_id_tasks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_task_collaborators_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_collaborators')),
    sa.UniqueConstraint('task_id', 'user_id', name='uq_task_collaborators_task_user')
    )
    op.create_index(op.f('ix_task_collaborators_task_id'), 'task_collaborators', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_collaborators_task_id'), table_name='task_collaborators')
    op.drop_table('task_collaborators')
    op.drop_index('ix_blockers_open', table_name='blockers')
    op.drop_table('blockers')
    op.drop_index('ix_tasks_team_status_due', table_name='tasks')
    op.drop_index('ix_tasks_session', table_name='tasks')
    op.drop_index('ix_tasks_project', table_name='tasks')
    op.drop_index('ix_tasks_owner_status', table_name='tasks')
    op.drop_index('ix_tasks_origin', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_idea_tags_idea_id'), table_name='idea_tags')
    op.drop_table('idea_tags')
    op.drop_index(op.f('ix_game_scores_game_play_id'), table_name='game_scores')
    op.drop_table('game_scores')
    op.drop_index('ix_decisions_team', table_name='decisions')
    op.drop_table('decisions')
    op.drop_index('ix_xp_events_subject_time', table_name='xp_events')
    op.drop_index('ix_xp_events_leaderboard', table_name='xp_events')
    op.drop_table('xp_events')
    op.drop_index(op.f('ix_session_participants_session_id'), table_name='session_participants')
    op.drop_table('session_participants')
    op.drop_index('ix_ideas_team_status', table_name='ideas')
    op.drop_index('ix_ideas_session', table_name='ideas')
    op.drop_table('ideas')
    op.drop_index('ix_game_plays_session', table_name='game_plays')
    op.drop_table('game_plays')
    op.drop_index(op.f('ix_agenda_items_session_id'), table_name='agenda_items')
    op.drop_table('agenda_items')
    op.drop_index('ix_activity_team_occurred', table_name='activity')
    op.drop_index('ix_activity_target', table_name='activity')
    op.drop_index('ix_activity_session_occurred', table_name='activity')
    op.drop_table('activity')
    op.drop_index('ix_achievement_awards_subject', table_name='achievement_awards')
    op.drop_table('achievement_awards')
    op.drop_index('uq_sessions_one_active_per_team', table_name='sessions', postgresql_where=sa.text("status = 'active' AND deleted_at IS NULL"))
    op.drop_index(op.f('ix_sessions_status'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_seasons_team_id'), table_name='seasons')
    op.drop_table('seasons')
    op.drop_table('projects')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_team_id'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_invites_team_id'), table_name='invites')
    op.drop_table('invites')
    op.drop_index(op.f('ix_guests_team_id'), table_name='guests')
    op.drop_table('guests')
    op.drop_table('game_questions')
    op.drop_index('ix_comments_target', table_name='comments')
    op.drop_table('comments')
    op.drop_table('teams')
    op.drop_index(op.f('ix_content_packs_game_definition_key'), table_name='content_packs')
    op.drop_table('content_packs')
    op.drop_index(op.f('ix_auth_sessions_user_id'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_table('xp_rules')
    op.drop_table('users')
    op.drop_table('organizations')
    op.drop_table('game_definitions')
    op.drop_table('achievements')
    # ### end Alembic commands ###
